services:
  mediafusion:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion
    restart: unless-stopped
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      mediafusion_mongodb:
        condition: service_healthy
      mediafusion_redis:
        condition: service_healthy
        
  mediafusion_scheduler:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion_scheduler
    command: ["dramatiq", "api.task", "-p", "1", "-t", "4"]
    restart: unless-stopped
    depends_on:
      mediafusion_mongodb:
        condition: service_healthy
      mediafusion_redis:
        condition: service_healthy
      
  browserless:
    image: ghcr.io/browserless/chromium
    container_name: browserless
    environment:
      - TIMEOUT=-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  mediafusion_mongodb:
    image: mongo:latest
    container_name: mediafusion_mongodb
    restart: unless-stopped
    volumes:
      - ./mediafusion/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mediafusion_redis:
    image: redis:latest
    container_name: mediafusion_redis
    restart: unless-stopped
    volumes:
      - ./mediafusion/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
