services:
  zilean:
    image: ipromknight/zilean:latest
    restart: unless-stopped
    container_name: zilean
    tty: true
    ports:
      - "${ZILEAN_PORT}:8181"
    environment:
      Zilean__EnableDashboard: ${ZILEAN_ENABLE_DASHBOARD}
      Zilean__Database__ConnectionString: Host=zilean_postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true;Timeout=30;CommandTimeout=3600
      Zilean__Imdb__UseAllCores: ${ZILEAN_IMDB_USE_ALL_CORES}
      Zilean__Imdb__UseLucene: ${ZILEAN_IMDB_USE_LUCENE}
      Zilean__Parsing__BatchSize: ${ZILEAN_PARSING_BATCH_SIZE}
      Zilean__Dmm_ScrapeSchedule: ${ZILEAN_DMM_SCRAPE_SCHEDULE}
    volumes:
      - ./zilean/tmp:/tmp
    depends_on:
      zilean_postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8181/healthchecks/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  zilean_postgres:
    image: postgres:17.2-alpine
    container_name: zilean_postgres
    restart: unless-stopped
    shm_size: 2G
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - zilean_db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  zilean_db:
